---
log4r_config:
  loggers:
    - name          : development
      level         : DEBUG
      trace         : 'false'
      outputters    : 
      # - console
      # - console_errors
      - development

    - name          : production
      level         : WARN
      trace         : 'false'
      outputters    : 
      # - console
      # - console_errors
      - production

  # define all outputters (incl. formatters)
  outputters:
    # - type: StdoutOutputter
    #   name: console
    #   only_at: 
    #     - INFO
    #     - WARN
    #   formatter:
    #     date_pattern: '%H:%M:%S'
    #     pattern     : '%l::%d:  %m'
    #     type        : PatternFormatter
    # 
    # - type: StderrOutputter
    #   name: console_errors
    #   only_at: 
    #     - ERROR
    #     - FATAL
    #   formatter:
    #     date_pattern: '%H:%M:%S'
    #     pattern     : '%l::%d:  %m'
    #     type        : PatternFormatter
      
    - type: FileOutputter
      name: development
      filename: "rails-cbu-development.log" # notice the file extension is needed! 
      trunc: false
      formatter:
        date_pattern: '%Y %m %d %H:%M:%S.%L %z'
        pattern     : '%d %l: %m'
        type        : PatternFormatter

    - type: FileOutputter
      name: production
      filename: "rails-cbu-production.log" # notice the file extension is needed! 
      trunc: false
      formatter:
        date_pattern: '%Y %m %d %H:%M:%S.%L %z'
        pattern     : '%d %l: %m'
        type        : PatternFormatter

